name: CGL
on:
  push:
    branches:
      - '**'

jobs:
  cgl:
    uses: konradmichalik/reusable-github-actions/.github/workflows/cgl.yml@7e9510ad26b6bc039a13aa4bd9fa44a1a0b723bc # main
    with:
      php-version: '8.4'
