name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']
        symfony_constraint: ['^5.0', '^6.0', '^7.0']
        prefer_stability: ['--prefer-lowest', '--prefer-stable']

      exclude:
        # Symfony 5.x is not compatible with PHP >= 8.1
        - php: '8.1'
          symfony_constraint: '^5.0'
        - php: '8.2'
          symfony_constraint: '^5.0'
        - php: '8.3'
          symfony_constraint: '^5.0'
        - php: '8.4'
          symfony_constraint: '^5.0'

        # Symfony 6.x is not compatible with PHP >= 8.3
        - php: '8.3'
          symfony_constraint: '^6.0'
        - php: '8.4'
          symfony_constraint: '^6.0'

        # Symfony 7.x is not compatible with PHP < 8.2
        - php: '8.1'
          symfony_constraint: '^7.0'

    name: PHP ${{ matrix.php }} / Symfony ${{ matrix.symfony_constraint }} ${{ matrix.prefer_stability == '--prefer-lowest' && '(lowest)' || '(highest)' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: libxml, simplexml # Required by composer.json
          tools: composer # Ensure composer is available

      - name: Install Composer dependencies
        run: composer update --no-interaction --no-progress --no-suggest ${{ matrix.prefer_stability }}
        env:
          # This is how we tell Composer to resolve Symfony dependencies to a specific major version
          # Composer will try to satisfy this constraint along with the existing ones in composer.json
          SYMFONY_REQUIRE: ${{ matrix.symfony_constraint }}

      - name: Run PHPUnit tests
        run: composer test
